baseURL = "https://yujinping.top" 
googleAnalytics = "" # UA-XXXXXXXX-X
languageCode = "zh-CN" 
theme = "maupassant" 
title = "风信子-技术笔记" 

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

#disqusShortname = "yourdiscussshortname" ## 是否开启disqus评论，不要和utteranc同时开启

[author]
name = "Mr.Yu"

[params]
author = "Mr.Yu" 
beian = "粤ICP备18158056号" 
busuanzi = false #启用不算子网页统计
description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、项目管理、软件架构、自动化测试等" 
# googleAd = "" #ca-pub-xxxxxxxxxxxxxx
keywords = "golang,go语言,go语言笔记,java,项目管理,软件架构,公众号,小程序,自动化测试" 
localSearch = true # 启用本地搜索
subtitle = "专注于Java、Go语言(golang)、移动互联网、项目管理、软件架构、自动化测试" 

# 这里我存放在了主题的static文件夹里，根目录的似乎也可以
#customCSS = ['douban.css', 'other.css']
# if ['custom.css'], load '/static/css/custom.css' file
#customJS = ['douban.js']
# if ['custom.js'], load '/static/js/custom.js' file

# 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
toc = true # 是否开启目录

## 友情链接，可以多个

[[params.links]]
name = "GIT 使用指南"
title = "GIT 使用指南"
url = "https://git-scm.com/book/zh/v2"

[[params.links]]
name = "Go语言"
title = "Go语言中文站"
url = "https://golang.google.cn/"

# ## 侧边栏广告位
# [[params.ads]]
# img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
# title = "【2019双12】ALL IN CLoud 低至1折"
# url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
# [[params.ads]]
# img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
# title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
# url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
# [[params.ads]]
# img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"
# title = "【渠道专享低折扣】11月特惠 限时2折"
# url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"

# ## 配置 utteranc评论,教程参考 https://utteranc.es/
# [params.utteranc]
# enable = false 
# issueTerm = "pathname" 
# repo = "your github repo" ##换成自己得
# theme = "github-light" 

## 开启版权声明，协议名字和链接都可以换
#[params.cc]
#link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
#name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"

## 配置代码高亮
[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = true
style = "dracula"
tabWidth = 4
## 配置网站菜单

[menu]

# [[menu.main]]
# identifier = "tools"
# name = "关于"
# url = "/about/"
# weight = 2

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 3

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 4
